- hosts: worker
  become: yes
  pre_tasks:
    - name: uninstall apache2
      apt: name=apache2 state=absent

  roles:
    - { role: nginx }
    - { role: php7.2 }
    - { role: git }
    - { role: composer }

  vars:
    sites: hackathon
    user_git: hackazer
    path_to_app: /var/www/web/Hackathon
    proxy_env: 'http://ITS-552132-2ec3c:fed34@proxy.its.ac.id:8080'

- hosts: db
  vars:
    proxy_env: 'http://ITS-552132-2ec3c:fed34@proxy.its.ac.id:8080'
    username: 'regal'
    password: 'bolaubi'
  roles:
    - { role: db }