---
- name: software
  become: yes
  environment: 
  apt: name={{ item }} state=latest update_cache=true
  with_items:
   - nginx
   - php7.2
   - php7.2-fpm
   - php7.2-mbstring
   - php7.2-cli
   - php7.2-xml
   - php7.2-gd
   - php7.2-zip
   - php7.2-mysql
   - composer
   - git